languageCode = "en"
languageName = "English"
weight = 1
title = "Offensive Programming Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"

  [params.author]
    name = "Semant1ka"
    bio = "Staff Developer. Writing about code, systems, and everything in between."
    links = [
      { linkedin = "https://www.linkedin.com/in/polinaslavskaya/" },
      { github = "https://github.com/Semant1ka" },
    ]
